export const botNames = [
	"Buffy Summers",
	"Hermione Granger",
	"Derek Zoolander",
	"Elle Woods",
	"Dr. Rumack",
	"Wade Wilson",
	"Chon Wang",
	"Regina George",
	"Ron Burgundy",
	"Lord Dark Helmet",
	"Edna Mode",
	"Randle McMurphy",
	"Optimus Prime",
	"Clarice Starling",
	"Norman Bates",
	"Groot",
	"Leslie Knope",
	"Gromit",
	"Red",
	"Samwise Gamgee",
	"Bilbo Baggins",
	"Katherine G. Johnson",
	"Ace Ventura",
	"Sarah Connor",
	"Axel Foley",
	"Elaine Benes",
	"Daenerys Targaryen",
	"Dorothy Gale",
	"Vito Corleone",
	"Arya Stark",
	"Shuri",
	"Shaun Riley",
	"Obi-Wan Kenobi",
	"Captain America",
	"Ferris Bueller",
	"Dorothy Vaughan",
	"Rocky Balboa",
	"Atticus Finch",
	"Brienne of Tarth",
	"Jules Winnfield",
	"Peter Venkman",
	"Gandalf",
	"Imperator Furiosa",
	"Forrest Gump",
	"Sansa Stark",
	"Patrick Bateman",
	"Rey",
	"Hannibal Lecter",
	"Doc Brown",
	"Rick Blaine",
	"Captain Jack Sparrow",
	"Ellen Ripley",
	"Mary Jackson",
	"Iron Man",
	"Marty McFly",
	"Michael Corleone",
	"Annalise Keating",
];
